import type { EnvReference } from "./types.js";

export function renderEnvExample(references: EnvReference[]): string {
  const groups = new Map<string, EnvReference[]>();
  const emittedNames = new Set<string>();

  for (const reference of references) {
    if (!groups.has(reference.file)) {
      groups.set(reference.file, []);
    }
    groups.get(reference.file)?.push(reference);
  }

  const lines = [
    "# Generated by envsample.",
    "# Values are intentionally blank. Do not paste secrets here.",
    ""
  ];

  for (const [file, fileReferences] of [...groups.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push("# " + file);

    const names = [...new Set(fileReferences.map((reference) => reference.name))]
      .filter((name) => !emittedNames.has(name))
      .sort();
    if (names.length === 0) {
      continue;
    }

    for (const name of names) {
      lines.push(name + "=");
      emittedNames.add(name);
    }

    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}

export function uniqueEnvNames(references: EnvReference[]): string[] {
  return [...new Set(references.map((reference) => reference.name))].sort();
}
